#!/bin/bash

GROOVY_VER=1.8.5
JAVA_DEBUG="-Dgroovy.grape.report.downloads=true"
JAVA_OPTS="-Dfile.encoding=utf8 $JAVA_OPTS"

BASE=$(cd `dirname $0`; pwd)
java $JAVA_OPTS $JAVA_DEBUG -cp "$BASE/lib/*" \
    -Dgroovy.base="$BASE" \
    -Dgrape.root="$BASE" \
    -Dgroovy.version=$GROOVY_VER \
    groovy.ui.GroovyMain "$BASE/groovy.gr" $*
